// 页面模版
define('mods/pc/pageTpl', function(require, exports, module) {
    /* beautify ignore:start */
    /* eslint-disable indent */
    var tpl = {
        mod: [
            // 签到2017
            '<div class="M17_sign" id="pl-imgBg">',
                '<div class="hd" id="sign-info">',
                    '<div class="balance">',
                        '<i class="icon_sn icon_sn_mi"></i><span data-role="text-points" id="lemiCount"></span>',
                    '</div>',
                    '<ul class="info">',
                        // '<li><a href="javascript:;"><i class="icon_sn icon_sn_mis"></i>乐米记录</a><i class="sp"></i></li>',
                        '<li>历史累计签到：<span data-role="text-total"></span> 天</li>',
                        '<li>您今天是第<span data-role="text-rank"></span> 位签到的乐迷</li>',
                    '</ul>',
                    '<div class="wether">',
                        '<i class="icon_w" data-role="weatherImg"></i>',
                        '<div class="location"><span data-role="city"></span><span data-role="weather"></span></div>',
                        '<div class="date" data-role="current-time"></div>',
                    '</div>',
                '</div>',
                '<div class="cnt" id="pl-sign-cal">',
                    // 日历
                    '<div class="cal">',
                        '<div class="year">',
                            '<a href="javascript:;" class="pre" data-role="btn-calendar-prev"></a>',
                            '<span data-role="text-date">2013</span>',
                            '<a href="javascript:;" class="nxt" data-role="btn-calendar-next"></a>',
                        '</div>',
                        '<ol class="week">',
                            '<li>Sun</li>',
                            '<li>Mon</li>',
                            '<li>Tue</li>',
                            '<li>Wed</li>',
                            '<li>Thu</li>',
                            '<li>Fri</li>',
                            '<li>Sat</li>',
                        '</ol>',
                        '<div class="day_wrap">',
                            '<div class="qd_sucess hide" data-role="sign-success">签到成功 <i data-role="lemi"></i></div>',
                            '<div class="day" data-role="table-calendar">',
                                '<ul>',
                                    '<li><span></span></li>',
                                    '<li><span></span></li>',
                                    '<li><span></span></li>',
                                    '<li><span></span></li>',
                                    '<li><span></span></li>',
                                    '<li><span></span></li>',
                                    '<li><span></span></li>',
                                '</ul>',
                                '<ul>',
                                    '<li><span></span></li>',
                                    '<li><span></span></li>',
                                    '<li><span></span></li>',
                                    '<li><span></span></li>',
                                    '<li><span></span></li>',
                                    '<li><span></span></li>',
                                    '<li><span></span></li>',
                                '</ul>',
                                '<ul>',
                                    '<li><span></span></li>',
                                    '<li><span></span></li>',
                                    '<li><span></span></li>',
                                    '<li><span></span></li>',
                                    '<li><span></span></li>',
                                    '<li><span></span></li>',
                                    '<li><span></span></li>',
                                '</ul>',
                                '<ul>',
                                    '<li><span></span></li>',
                                    '<li><span></span></li>',
                                    '<li><span></span></li>',
                                    '<li><span></span></li>',
                                    '<li><span></span></li>',
                                    '<li><span></span></li>',
                                    '<li><span></span></li>',
                                '</ul>',
                                '<ul>',
                                    '<li><span></span></li>',
                                    '<li><span></span></li>',
                                    '<li><span></span></li>',
                                    '<li><span></span></li>',
                                    '<li><span></span></li>',
                                    '<li><span></span></li>',
                                    '<li><span></span></li>',
                                '</ul>',
                                '<ul>',
                                    '<li><span></span></li>',
                                    '<li><span></span></li>',
                                    '<li><span></span></li>',
                                    '<li><span></span></li>',
                                    '<li><span></span></li>',
                                    '<li><span></span></li>',
                                    '<li><span></span></li>',
                                '</ul>',
                            '</div>',
                        '</div>',
                    '</div>',
                    // 日历
                    // 任务
                    '<div class="main_cnt">',
                        '<div class="task" id="pl-task">',
                            '<div class="main_tl">',
                            '每日任务',
                            '</div>',
                            '<div class="task_lst" data-role="list"></div>',
                        '</div>',
                        '<div class="slide">',
                            '<div class="main_tl">',
                            '大家都在看',
                            '</div>',
                            '<div class="slide_lst" id="pl-recommend">',
                                '<ul class="clearfix" data-role="list"></ul>',
                                '<ul class="piclist swaplist" data-role="swaplist"></ul>',
                                '<a class="scroll_btn prebtn" data-role="prebtn" href="javascript:void(0)"></a>',
                                '<a class="scroll_btn nxtbtn" data-role="nxtbtn" href="javascript:void(0)"></a>',
                            '</div>',
                            '<div class="qr" id="pl-qr">',
                                '<div class="qr_cnt">',
                                    '<a href="http://h5.bbs.le.com/wish/?ref=lemeqd" data-role="wish-link" target="_blank" class="get_bd"></a>',
                                    '<span>用乐迷APP</span> 赚取更多乐米 更开心！<i class="icon_sn icon_sn_qr" data-role="qr_btn"></i>',
                                    '<div class="qr_img hide" data-role="qr_img">',
                                        '<img src="http://i2.letvimg.com/lc05_iscms/201702/24/11/14/a836b38487b44f70b89edb206b46defe.png" />',
                                    '</div>',
                                '</div>',
                            '</div>',
                        '</div>',
                    '</div>',
                    // 任务
                '</div>',
            '</div>'
        ].join(''),
        extraGift: [
            '<div class="gift_wrap hide" data-role="extra">',
                '<i class="gift_mi"></i>',
            '</div>'
        ].join('')
    };
    /* beautify ignore:end */
    /* esling-disable indent */
    module.exports = tpl;
});
