/**
 * @fileoverview 各模块模板
 * @authors liyifei@le.com
 * @date 2017/03
 */
define('mods/mobile/pageTpl', function(require, exports, module) {
    /* beautify ignore:start */
    /* eslint-disable indent */
    var tpl = {
        mod: [
            // 底部图片
            '<div id="pl-layer-cover" class="L_bg" style="display:none;"></div>',
            // 引导层
            '<div id="pl-layer-guide" class="L_guide" style="display:none;">',
                '<div class="a"></div>',
                '<div class="b"></div>',
            '</div>',

            // 动画-红包雨
            '<div id="pl-ani-rain" class="L_ani" style="display:none;">',
                '<div class="clipped-box" data-role="donghua">',
                    // '<div class="content"></div>',
                '</div>',
            '</div>',

            // 签到浮层
            // 点击签到
            '<div id="pl-dosign" class="L_ac" style="display:none;">',
                '<a href="javascript:;" class="ac_cnt">',
                    '<i class="icon_active"></i> 点击签到',
                '</a>',
            '</div>',
            // 签到成功
            '<div id="pl-sign-succ" class="L_sucess" style="display:none;">',
                '<div class="suc_box">',
                    '<div class="gift">',
                        '<img src="http://i1.letvimg.com/lc04_iscms/201704/07/14/25/8963b631974d427fb90ee6103d6a45d3.jpg">',
                    '</div>',
                    '<div class="qd">',
                        '<div class="qd_tl">签到成功</div>',
                        '<div class="benefit">获得<span data-role="lemi"></span>乐米</div>',
                        '<div class="pro">本月连续签到：<span><i data-role="sign-cur-lasted"></i>天</span><span class="hide" data-role="sign-extra">额外奖励<i></i>乐米！</span></div>',
                    '</div>',
                    '<div class="yunshi">',
                        '<div class="item">',
                            '<span>今日运势:</span><span data-role="text-luck"></span><a href="javascript:;"></a>',
                            '<div class="source">来源：科技紫微星座网</div>',
                        '</div>',
                        '<div class="item">',
                            '<span data-role="city"></span><i class="icon_w" data-role="weatherImg"></i><span data-role="weather"></span><span data-role="current-time">10月5日</span>',
                            '<div class="source">来源：天气通</div>',
                        '</div>',
                    '</div>',
                '</div>',
                '<a href="javascript:;" data-role="btn-close" class="C_f_cls"></a>',
            '</div>',

            // 签到日历浮层
            '<div id="pl-sign-cal" class="L_cal" style="display:none;">',
                '<div class="cal_box">',
                    '<div class="outline">',
                        '<div>您累计签到：<span class="num" data-role="text-total"></span> 天</div>',
                        '<div>本月连续签到：<span data-role="text-lasted"></span> 天</div>',
                        '<div>您今天是第 <span data-role="text-rank"></span> 位签到的乐迷！</div>',
                    '</div>',
                    '<div class="tab">',
                        '<div class="year">',
                            '<a href="javascript:;" class="pre" data-role="btn-calendar-prev"></a><span data-role="text-date"></span>',
                            '<a href="javascript:;" class="nxt" data-role="btn-calendar-next"></a>',
                        '</div>',
                        '<ol class="week">',
                            '<li>Sun</li>',
                            '<li>Mon</li>',
                            '<li>Tue</li>',
                            '<li>Wed</li>',
                            '<li>Thu</li>',
                            '<li>Fri</li>',
                            '<li>Sat</li>',
                        '</ol>',
                        '<div class="day_wrap">',
                            '<table class="day" data-role="table-calendar">',
                                '<tr>',
                                    '<td><span></span></td>',
                                    '<td><span></span></td>',
                                    '<td><span></span></td>',
                                    '<td><span></span></td>',
                                    '<td><span></span></td>',
                                    '<td><span></span></td>',
                                    '<td><span></span></td>',
                                '</tr>',
                                '<tr>',
                                    '<td><span></span></td>',
                                    '<td><span></span></td>',
                                    '<td><span></span></td>',
                                    '<td><span></span></td>',
                                    '<td><span></span></td>',
                                    '<td><span></span></td>',
                                    '<td><span></span></td>',
                                '</tr>',
                                '<tr>',
                                    '<td><span></span></td>',
                                    '<td><span></span></td>',
                                    '<td><span></span></td>',
                                    '<td><span></span></td>',
                                    '<td><span></span></td>',
                                    '<td><span></span></td>',
                                    '<td><span></span></td>',
                                '</tr>',
                                '<tr>',
                                    '<td><span></span></td>',
                                    '<td><span></span></td>',
                                    '<td><span></span></td>',
                                    '<td><span></span></td>',
                                    '<td><span></span></td>',
                                    '<td><span></span></td>',
                                    '<td><span></span></td>',
                                '</tr>',
                                '<tr>',
                                    '<td><span></span></td>',
                                    '<td><span></span></td>',
                                    '<td><span></span></td>',
                                    '<td><span></span></td>',
                                    '<td><span></span></td>',
                                    '<td><span></span></td>',
                                    '<td><span></span></td>',
                                '</tr>',
                                '<tr>',
                                    '<td><span></span></td>',
                                    '<td><span></span></td>',
                                    '<td><span></span></td>',
                                    '<td><span></span></td>',
                                    '<td><span></span></td>',
                                    '<td><span></span></td>',
                                    '<td><span></span></td>',
                                '</tr>',
                            '</table>',
                        '</div>',
                    '</div>',
                '</div>',
                '<a href="javascript:;" data-role="btn-close" class="C_f_cls"></a>',
            '</div>',

            // 主页面
            '<div id="pl-main" style="display:none;">',
                // 页面头部
                '<div id="pl-head" class="M_head">',
                    '<div class="top clearfix">',
                        '<div class="name" data-role="userinfo"></div>',
                        // '<div class="alert"><span>签到提醒</span><a href="javascript:;" data-role="btn-push" class="check checked"><i></i></a></div>',
                    '</div>',
                    '<div class="lasted">',
                        '<div class="l_tl">本月已连续签到</div>',
                        '<div class="num_wrap" data-role="sign-days"></div>',
                    '</div>',
                    '<div class="steps">',
                        '<div class="bar" data-role="cur-bar">',
                            '<span></span>',
                        '</div>',
                        '<div class="arrow" data-role="btn-arrow"></div>',
                        '<div class="date" data-role="cur-calendar">',
                            '<div class="month" data-role="cur-month"></div>',
                            '<div class="days clearfix" data-role="cur-days-bar">',
                                '<div class="clearfix" style="width: 1500px;" data-role="cur-days">',
                                '</div>',
                            '</div>',
                        '</div>',
                    '</div>',
                '</div>',
                // 我的乐米部分
                '<div id="pl-account" class="M_account">',
                    '<div class="F_cnt">',
                        '<div class="balance">我的乐米：<i data-role="text-points"></i></div>',
                        // '<a href="javascript:;">乐迷记录</a>',
                        // '<a href="http://shop.bbs.letv.com/site/default">乐迷集市</a>',
                        '<a href="http://h5.bbs.le.com/wish/?ref=lemeqd" data-role="wish-link"><i class="icon_crown"></i><span>领专属头像</span></a>',
                    '</div>',
                '</div>',
                // 任务模块
                '<div id="pl-task" class="M_task F_cnt">',
                    '<div class="C_maintl"><span>今日任务</span>',
                        '<a class="toggle toggle_up" data-role="btn-toggle" href="javascript:;"></a>',
                    '</div>',
                    '<div class="" data-role="list"></div>',
                '</div>',
                // 大家都在看推荐模块
                '<div id="pl-recommend" class="M_slide F_cnt">',
                    '<div class="C_maintl">大家都在看</div>',
                    '<div class="slide clearfix">',
                        '<ul class="clearfix" data-role="list" style="width: 100rem">',
                        '</ul>',
                    '</div>',
                '</div>',
                // 排行榜模块
                '<div id="pl-new" class="M_rank F_cnt hide">',
                    '<div class="C_maintl">今日任务完成光荣榜</div>',
                    '<div class="lst_wrap C_item">',
                        '<ol class="lst " data-role="honer_list">',
                        '</ol>',
                    '</div>',
                '</div>',
            '</div>'
        ].join(''),
        extraGift: [
            '<div class="gift_wrap hide" data-role="extra">',
                '<i class="gift_mi"></i>',
            '</div>'
        ].join('')
    };
    /* beautify ignore:end */
    /* esling-disable indent */

    module.exports = tpl;
});
